on:
  pull_request:
  push:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Execute script
        working-directory: /
        run: |
          python3 add_language.py
        
      - name: Commit files
        working-directory: /
        run: |
          git add README.md
          git commit -m "📝 updated language list" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflow-test
